services:
  - type: web
    name: bouncer
    env: rust
    buildCommand: cargo build --release
    startCommand: ./target/release/bouncer
    envVars:
      - key: ROCKET_ADDRESS
        value: 0.0.0.0
      - key: ROCKET_PORT
        fromService:
          type: web
          name: bouncer
          envVarKey: PORT
      # Add your database URL if you're using one
      - key: DATABASE_URL
        sync: false # This means you'll set it manually in Render dashboard
    autoDeploy: true 